### ISSUE TITLE
[Mbed-OS-5.9.0-OoB] export make_gcc_arm; build fails on Windows.

### ISSUE THREAD

**Issue by coisme** [ARMmbed/mbed-os-example-nvstore#16] opened 2018-06-05 08:26 UTC
# Bug
When I tried the export command on Windows 7, I got an error on build. This doesn't happen on macOS.

## Steps to reproduce:
`mbed import mbed-os-example-nvstore`
`mbed update mbed-os-5.9.0-oob`
`mbed export -i make_gcc_arm -m K66F`
`make`

## Error message:
> make (e=87): The parameter is incorrect.
> make[1]: *** [mbed-os-example-nvstore.elf] Error 87
> make: *** [all] Error 2

Full error log [report2.txt](https://github.com/ARMmbed/mbed-os-example-nvstore/files/2071449/report2.txt)

## Version Hash
> mbed-os-example-nvstore (#b2a60ea4eb41, tag: mbed-os-5.9.0-rc1)
> `- mbed-os (#6817dc43f9f5, tag: mbed-os-5.9.0-rc1)

cc @MarceloSalazar

**Comment by adbridge** [comment] 2018-06-05 15:05
@theotherjimmy Is this another windows command length error?

**Comment by theotherjimmy** [comment] 2018-06-05 15:30
Yes

**Comment by adbridge** [comment] 2018-06-05 15:55
Related to  https://github.com/ARMmbed/mbed-os/issues/6335

**Comment by ciarmcom** [comment] 2018-06-07 15:51
ARM Internal Ref: MBOTRIAGE-587

**Comment by cmonr** [comment] 2018-06-07 15:53
@davidsaada Please close as this is a duplicate of another issue.

**Closed as completed** 2018-06-07 15:53 UTC
Labels: mirrored, closed_in_jira

**Comment by mikkeaa** [comment] 2018-07-02 13:42
Please **REMOVE** the tutorial howto use Eclipse in windows !!!

**Comment by theotherjimmy** [comment] 2018-07-02 14:53
@mikkeaa You may have better luck if you open a new issue (on mbed-os or mbed-os-5-docs), and you explain why you would like it removed.

**Comment by mikkeaa** [comment] 2018-07-02 15:16
It's not really an issue in my opinion, but an old crappy windows-dos feature on max path length etc.
And there's no cure for this problem I suppose.
-The tutorial at mbed-os for eclipse will always lead to this, if you use defaults. So it feels a bit stupid to fail overhere and read this... and ok, this was it, not possible...
