### ISSUE TITLE
Printings are messy

### ISSUE THREAD

**Issue by kseverinkangas-zg** [ARMmbed/mbed-os-example-nvstore#3] opened 2018-03-07 08:14 UTC
On the console the line breaks do not go very nicely.
Also it would be useful to do some checks of written and read values and raise an error if condition is not ok.

**Comment by davidsaada** [comment] 2018-03-08 14:47
> Also it would be useful to do some checks of written and read values and raise an error if condition is not ok.

This was actually the original code, but removed it after a comment from @MarceloSalazar - claiming that the code should be much easier to understand. If you look at [this commit](https://github.com/ARMmbed/mbed-os-example-nvstore/commit/5a46c69ba6e3105976acbac2608991be03b0e580) you'll see the changes.

**Comment by davidsaada** [comment] 2018-03-09 14:17
> On the console the line breaks do not go very nicely.

@karsev Have you tried it with the K64F board? And what host environment are you viewing the prints on? Can you give an example for such a messy print? Viewing it via putty in Linux looks fine to me.

**Comment by kseverinkangas-zg** [comment] 2018-03-12 09:11
I run the example on windows using Putty.
You need to add this to your .json -> "platform.stdio-convert-newlines": 1
Then the carriage returns ("\r") are automatically added.

**Comment by davidsaada** [comment] 2018-03-12 09:25
Does the output look like the way showed before or after the addition to JSON?
Because this is just the way it should look like.

**Comment by kseverinkangas-zg** [comment] 2018-03-12 09:43
Sorry, I forgot to verify how it looks like here. I cannot copy paste the result here, it gets auto formatted.
But, yes it should look like it was there. So just add the conf to .json and it should be fine.

**Comment by davidsaada** [comment] 2018-03-12 10:08
Fixed and verified here (apparently my putty was configured to add these line breaks by itself). Please check that it also fixes the issue on your end.

**Comment by kseverinkangas-zg** [comment] 2018-03-12 11:07
This is good now!

**Comment by adbridge** [comment] 2018-03-12 14:42
If the issue is fixed can we close this then please ?

**Closed as completed** 2018-03-12 14:42 UTC
