### ISSUE TITLE
NRF52_DK build made with make_iar does not start

### ISSUE THREAD

**Issue by artokin** [ARMmbed/mbed-os-example-nvstore#7] opened 2018-03-07 13:55 UTC
Build failed to start when build was made with exporter: `mbed export -i make_iar -m NRF52_DK`.
Binary or hex file can be programmed successfully but the build does not start.

**Comment by theotherjimmy** [comment] 2018-03-08 15:06
Does this only affect `make_iar` with `NRF52_DK`? or does it also affect `make_gcc_arm` and `make_armc5`? does it affect any other targets?

**Comment by davidsaada** [comment] 2018-03-09 13:00
Fixed in latest commit.

**Comment by theotherjimmy** [comment] 2018-03-09 16:19
@davidsaada Could you explain what the problem was? @artokin Does this new commit resolve the issue?

**Comment by davidsaada** [comment] 2018-03-09 18:21
@theotherjimmy It was actually not an issue with export only, but with build as well, for all boards that didn't support NVStore. Had to enclose all the code that referred to NVStore with the `NVSTORE_ENABLED` define.

**Comment by davidsaada** [comment] 2018-03-12 14:48
This was fixed in commit `904f622`. @artokin Please confirm it works (checked it locally).

**Comment by ashok-rao** [comment] 2018-03-21 17:08
@adbridge , I confirm the issue is fixed in RC2. This can now be closed.

**Closed as completed** 2018-06-07 15:41 UTC
